#pragma once

#include "imgui.h"

namespace sokoke {

void ApplyAMOLEDTheme() {
    // AMOLED theme — pure black backgrounds, orange active highlights
    // generated by Claude Code.
    ImGuiStyle& style = ImGui::GetStyle();
    ImVec4* colors = style.Colors;

    // Text
    colors[ImGuiCol_Text]                       = ImVec4(0.92f, 0.92f, 0.92f, 1.00f);
    colors[ImGuiCol_TextDisabled]               = ImVec4(0.38f, 0.38f, 0.38f, 1.00f);
    colors[ImGuiCol_TextLink]                   = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Backgrounds
    colors[ImGuiCol_WindowBg]                   = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
    colors[ImGuiCol_ChildBg]                    = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
    colors[ImGuiCol_PopupBg]                    = ImVec4(0.04f, 0.04f, 0.04f, 1.00f);

    // Borders
    colors[ImGuiCol_Border]                     = ImVec4(0.18f, 0.18f, 0.18f, 1.00f);
    colors[ImGuiCol_BorderShadow]               = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);

    // Frames (inputs, sliders, checkboxes)
    colors[ImGuiCol_FrameBg]                    = ImVec4(0.08f, 0.08f, 0.08f, 1.00f);
    colors[ImGuiCol_FrameBgHovered]             = ImVec4(0.14f, 0.14f, 0.14f, 1.00f);
    colors[ImGuiCol_FrameBgActive]              = ImVec4(1.00f, 0.60f, 0.00f, 0.25f);

    // Title bars
    colors[ImGuiCol_TitleBg]                    = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
    colors[ImGuiCol_TitleBgActive]              = ImVec4(0.06f, 0.06f, 0.06f, 1.00f);
    colors[ImGuiCol_TitleBgCollapsed]           = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);

    // Menu bar
    colors[ImGuiCol_MenuBarBg]                  = ImVec4(0.04f, 0.04f, 0.04f, 1.00f);

    // Scrollbar
    colors[ImGuiCol_ScrollbarBg]                = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
    colors[ImGuiCol_ScrollbarGrab]              = ImVec4(0.22f, 0.22f, 0.22f, 1.00f);
    colors[ImGuiCol_ScrollbarGrabHovered]       = ImVec4(0.35f, 0.35f, 0.35f, 1.00f);
    colors[ImGuiCol_ScrollbarGrabActive]        = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Interactive widgets
    colors[ImGuiCol_CheckMark]                  = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_SliderGrab]                 = ImVec4(0.60f, 0.36f, 0.00f, 1.00f);
    colors[ImGuiCol_SliderGrabActive]           = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Buttons
    colors[ImGuiCol_Button]                     = ImVec4(0.10f, 0.10f, 0.10f, 1.00f);
    colors[ImGuiCol_ButtonHovered]              = ImVec4(1.00f, 0.60f, 0.00f, 0.20f);
    colors[ImGuiCol_ButtonActive]               = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Headers (collapsing headers, tree nodes, selectables, menu items)
    colors[ImGuiCol_Header]                     = ImVec4(1.00f, 0.60f, 0.00f, 0.15f);
    colors[ImGuiCol_HeaderHovered]              = ImVec4(1.00f, 0.60f, 0.00f, 0.25f);
    colors[ImGuiCol_HeaderActive]               = ImVec4(1.00f, 0.60f, 0.00f, 0.45f);

    // Separators
    colors[ImGuiCol_Separator]                  = ImVec4(0.18f, 0.18f, 0.18f, 1.00f);
    colors[ImGuiCol_SeparatorHovered]           = ImVec4(1.00f, 0.60f, 0.00f, 0.60f);
    colors[ImGuiCol_SeparatorActive]            = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Resize grip
    colors[ImGuiCol_ResizeGrip]                 = ImVec4(1.00f, 0.60f, 0.00f, 0.15f);
    colors[ImGuiCol_ResizeGripHovered]          = ImVec4(1.00f, 0.60f, 0.00f, 0.50f);
    colors[ImGuiCol_ResizeGripActive]           = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Tabs
    colors[ImGuiCol_Tab]                        = ImVec4(0.06f, 0.06f, 0.06f, 1.00f);
    colors[ImGuiCol_TabHovered]                 = ImVec4(1.00f, 0.60f, 0.00f, 0.25f);
    colors[ImGuiCol_TabSelected]                = ImVec4(0.12f, 0.12f, 0.12f, 1.00f);
    colors[ImGuiCol_TabSelectedOverline]        = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_TabDimmed]                  = ImVec4(0.03f, 0.03f, 0.03f, 1.00f);
    colors[ImGuiCol_TabDimmedSelected]          = ImVec4(0.08f, 0.08f, 0.08f, 1.00f);
    colors[ImGuiCol_TabDimmedSelectedOverline]  = ImVec4(0.50f, 0.30f, 0.00f, 1.00f);

    // Docking
    colors[ImGuiCol_DockingPreview]             = ImVec4(1.00f, 0.60f, 0.00f, 0.35f);
    colors[ImGuiCol_DockingEmptyBg]             = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);

    // Plots
    colors[ImGuiCol_PlotLines]                  = ImVec4(0.55f, 0.55f, 0.55f, 1.00f);
    colors[ImGuiCol_PlotLinesHovered]           = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogram]              = ImVec4(0.60f, 0.36f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogramHovered]       = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);

    // Tables
    colors[ImGuiCol_TableHeaderBg]              = ImVec4(0.06f, 0.06f, 0.06f, 1.00f);
    colors[ImGuiCol_TableBorderStrong]          = ImVec4(0.20f, 0.20f, 0.20f, 1.00f);
    colors[ImGuiCol_TableBorderLight]           = ImVec4(0.12f, 0.12f, 0.12f, 1.00f);
    colors[ImGuiCol_TableRowBg]                 = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
    colors[ImGuiCol_TableRowBgAlt]              = ImVec4(1.00f, 1.00f, 1.00f, 0.03f);

    // Misc interaction
    colors[ImGuiCol_TextSelectedBg]             = ImVec4(1.00f, 0.60f, 0.00f, 0.25f);
    colors[ImGuiCol_DragDropTarget]             = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_NavCursor]                  = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_NavWindowingHighlight]      = ImVec4(1.00f, 0.60f, 0.00f, 0.70f);
    colors[ImGuiCol_NavWindowingDimBg]          = ImVec4(0.00f, 0.00f, 0.00f, 0.60f);
    colors[ImGuiCol_ModalWindowDimBg]           = ImVec4(0.00f, 0.00f, 0.00f, 0.70f);

    // Style variables
    style.WindowRounding     = 4.0f;
    style.ChildRounding      = 4.0f;
    style.FrameRounding      = 3.0f;
    style.PopupRounding      = 4.0f;
    style.ScrollbarRounding  = 9.0f;
    style.GrabRounding       = 3.0f;
    style.TabRounding        = 4.0f;
    style.WindowBorderSize   = 1.0f;
    style.FrameBorderSize    = 0.0f;
    style.TabBorderSize      = 0.0f;
}

}